### ISSUE TITLE
Support for Proxy

### ISSUE THREAD

**Issue by YuriRudenyaDev** [splitio/android-client#155]
SplitIO doesn't work when an android phone connected to wifi with NTLM Proxy.
We had the same issue before stated working with SplitIO SDK but we used the retrofit SDK.

OkHTTP client builder:

    public OkHttpClient createClient(boolean loggingEnabled, boolean tls12Enforced, int connectTimeout, int readTimeout, int writeTimeout) {

        OkHttpClient.Builder defaultHttpClient = new OkHttpClient.Builder();

        Authenticator proxyAuthenticator = new Authenticator() {

            @Override
            public Request authenticate(Route route, okhttp3.Response response) throws IOException {
                if (response.code() == 407) {

                    ProxyCredentials credentials = getProxyCredentials();

                    if (credentials == null) {
                        throw new IOException("Failed to authenticate with proxy");
                    }

                    List<HTTPAuthMethod> httpAuthMethods = HTTPAuthMethod.ReadMethodsFromResponse(response);
                    ProxyAuthenticator resolvedAuthenticator = null;
                    HTTPAuthMethod resolvedMethod = null;
                    for (ProxyAuthenticator authenticator : proxyAuthenticators) {
                        for (HTTPAuthMethod authMethod : httpAuthMethods) {
                            if (authenticator.supportsAuthMethod(authMethod)) {
                                resolvedAuthenticator = authenticator;
                                resolvedMethod = authMethod;

                                break;
                            }
                        }

                        if (resolvedAuthenticator != null) {
                            break;
                        }
                    }

                    if (resolvedAuthenticator == null) {
                        return null;
                    }

                    try {
                        return resolvedAuthenticator.authenticate(credentials, resolvedMethod, route, response);
                    } catch (Throwable e) {
                        if (e instanceof ProxyErrors.CredentialsAreInvalidException) {
                            updateProxyCredentials(null);
                        }

                        throw new IOException("Failed to authenticate with proxy");
                    }
                }

                return null;
            }
        };

        defaultHttpClient = defaultHttpClient
                .proxyAuthenticator(proxyAuthenticator);

        return modifyClient(defaultHttpClient.build(), loggingEnabled, tls12Enforced, connectTimeout, readTimeout, writeTimeout);
    }
            @Override
            public void onFailure(Call<T> call, Throwable t) {
                t.printStackTrace();
                if (result == null) {
                    return;
                } else if ("Canceled".equalsIgnoreCase(t.getMessage())) {
                    return;
                }

                if (t.getMessage() != null && t.getMessage().equals("Failed to authenticate with proxy")) {
                    handleProxyError(call, result, context, t);
                    return;
                }

                notifyErrorResult(call, result, context, t);
            }
    public static <T> void handleProxyError(final Call<T> call, final CallbackResponse<T> result, final Context context, final Throwable error) {
        if (instance.proxyErrorHandler == null) {
            notifyErrorResult(call, result, context, error);
            return;
        }

        ErrorRequestFulfiller fulfiller = new ErrorRequestFulfiller() {
            @Override
            void notifyError() {
                notifyErrorResult(call, result, context, error);
            }

            @Override
            void redo() {
                enqueue(call.clone(), result, context);
            }
        };

        inflightRequests.add(fulfiller);

        if (handlingProxyError) {
            return;
        }

        handlingProxyError = true;
        instance.proxyErrorHandler.handle(new ProxyErrorHandler.Callback() {
            @Override
            public void onResult(ProxyErrorHandler.Result resolveResult) {
                handlingProxyError = false;

                if (resolveResult.getError() != null) {
                    for (ErrorRequestFulfiller fulfiller : inflightRequests) {
                        fulfiller.notifyError();
                    }
                } else {
                    ProxyData proxyData = resolveResult.getProxyData();
                    ProxyCredentials credentials = new ProxyCredentials(proxyData.getProxyUser(), proxyData.getProxyPass());
                    instance.updateProxyCredentials(credentials);
                    for (ErrorRequestFulfiller fulfiller : inflightRequests) {
                        fulfiller.redo();
                    }
                }
            }
        });
    }

In case of a proxy authentication error, we show a dialog and ask users to enter a login/password to save it for the current and next session.

Environment

Android:
implementation 'io.split.client:android-client:2.4.5'

NTLM setup on a local machine for testing

Requirements:

Windows
I use parallels, install windows there, establish a connection between host and virtual machine (ping to check)

Steps:

Install WinGate
a) https://www.wingate.com/download/wingate/download.php?gclid=EAIaIQobChMI0bbYzoT14wIVlOiaCh1XzQ_EEAAYASABEgIioPD_BwE

Start Wingate
a) Select the first square button
b) In wizard select win proxy as a provider (should be automatically though)
c) Select + on the same screen where we selected the first button and click on in popup
d). Select the created a button and choose to Use another account
e) Name: Administrator, Pass:

Enable NTLM and Select Port
a) Control panel -> services -> www proxy
b) In General select port (let's say 9020), enable NTLM, disable basic (we want to check NTLM right?)

Force NTLM authentication
a) Right-click, new policy.
b) Source Type: Any HTTPProxy, Event type: Request.
c) The easiest way to configure policy is to drag and drop some policy elements from other policies.
d) To do this Open web authenticate policy in another window (you can see this policy in the list)
e) Drag and drop to a new policy from authenticating policy: "Auth", "Allow", "Is authenticated?" elements.
f) Drag and drop to new policy from a list of elements "WWW Proxy Server: Request" element.
g) Connect "WWW Proxy Server: Request" to "Is authenticated" element
h) Connect the bottom of "Is authenticated" (Yes) to "Allow" element
i) Connect right of "Is authenticated" (No) to "Auth" element
j) Save (the policy will start to work automatically)

Create user.
a) Control Panel -> Users and Groups
b) Right-click -> new Users
c) Fill in name pass etc.

Check (For mac).

Add proxy.
a) Go to settings -> Network -> Choose network used for internet -> Advanced -> Proxy
b) Fill in IP and port of proxy for Web Proxy and Secure Web Proxy (Do not fill in pass etc)
Check proxy is used
c) Go to, say, google.com.
d) Name and Pass requests should be requested.
e) Use ones from 5.iii
Check (For Android Device and Wingate is on a virtual machine).

Add Proxy in android Settings
Add port forwarding to port selected on step 3(b)
Warnings.

Wingate caches auth status. To force re-auth change user password 5(c) and restart WinGate (Kill Wingate Manager from Tasks Manager (Ctrl + Shift + Esc))

**Comment by chillaq** [comment]
Hi Yuri, thanks for the details, we are looking into this, will get back to you once I have an update.

Thanks
Bilal

**Comment by jalleyne** [comment]
Hi @chillaq, any updates on this?

**Comment by chillaq** [comment]
We are working on it, ETA is next week.

**Comment by javrudsky** [comment]
A fix was issued for this ticket. Closing it because it has been inactive for one year.
