### ISSUE TITLE
Seeing a lot of errors from split sdk on Android in my logcat

### ISSUE THREAD

**Issue by KarimFikani** [splitio/android-client#173]
Hey,

Today I realized that I'm seeing a lot of errors related to the latest split sdk (2.6.0) on Android that I can barely use my logcat for anything else.

```
 E/SplitSDK: Invalide SSE event received: STREAMING_CONNECTED
 E/SplitSDK: An error has ocurred while parsing stream from https://split-realtime.ably.io/sse : Socket closed
 I/SplitSDK: Periodic fetcher tasks scheduled
 I/SplitSDK: Polling enabled.
 I/SplitSDK: Streaming connection opened
 I/SplitSDK: Sending polling disabled message through event broadcaster.
 I/SplitSDK: Stoping periodic fetching tasks 01d327b2-9c99-4fec-8c74-2b9406689649, 4bee70a9-5afc-4fae-87be-5c4438e20b2c
 I/SplitSDK: Polling disabled.
 I/SplitSDK: Disabling polling
 E/SplitSDK: Invalide SSE event received: STREAMING_CONNECTED
```
Any reason why they are showing up and how can we turn them off?

**Comment by chillaq** [comment]
Hi Karim, this might be related to the new PUSH feature in Android SDK we released, this feature is suppose to be disabled by default, as seen in our docs: https://help.split.io/hc/en-us/articles/360020343291-Android-SDK#configuration

Can you manually set the config parameter "streamingEnabled" to "false" just to confirm that it is disabled, then let me know if you see the errors again?

Thanks
Bilal

**Comment by chillaq** [comment]
Hi Karim, Just following up on this issue, do you still need any more help?

Thanks
Bilal

**Comment by KarimFikani** [comment]
Don't see those anymore. Will open again if I see them
