### ISSUE TITLE
Split 2.6.1 crashes on Android 4

### ISSUE THREAD

**Issue by leonardoxh** [splitio/android-client#179]
Split 2.6.1 crashes on Android 4, I looked at split changelog + dependencies and this is simply because the OkHttp dependency that split uses is 4+

To keep support to android 4 the dependency should be 3.12+

https://cashapp.github.io/2019-02-05/okhttp-3-13-requires-android-5

**Comment by chillaq** [comment]
Hi Leonardo, thanks for the details, we are checking this issue now.

**Comment by leonardoxh** [comment]
Any news here ?

**Comment by chillaq** [comment]
Hi Leonardo, we are still working on it, we suspect the issue related to instantiating the SDK in a background thread, and the work manager seem to not be allowed to start there, we have multiple options to resolve it, will let you know once I get more updates.

Thanks
Bilal

**Comment by leonardoxh** [comment]
hm,

I feel this is something else... I cant even start split on a android 4 target due this okhttp crash, I  think as split uses a newer dependency of okhttp it overrides mine causing this issue

**Comment by chillaq** [comment]
Ah sorry Leonardo, was meant to say we did downgrade the OKHttp lib to resolve this issue, we actually had a non-fatal crash issue that we are working on right now to include it in the fix. No firm ETA yet, but hopefully within next week.

Thanks
Bilal

**Comment by NicoZelaya** [comment]
Hi @leonardoxh !

We've released version 2.6.2 including the downgrade Bilal told you about (among other things). 
Please, do give it a try and let us know if you're still experiencing the crash for Android 4, we'll keep the issue open for now. 

Our apologies for the inconveniences! 
Nico.

**Comment by leonardoxh** [comment]
it works perfectly @NicoZelaya, I think we can close this one

**Comment by NicoZelaya** [comment]
Glad to hear! I will go ahead and close it then. 

Enjoy the rest of your week!
