### ISSUE TITLE
Obfuscation problems

### ISSUE THREAD

**Issue by jordansilva** [splitio/android-client#184]
Could you update the proguard rules file?
I'm trying to run Split.io with proguard but it was crashing on startup.
After adding those lines below, the crash stopped, but Split.io doesn't retrieve any Treatment when it is obfuscated.
```
-keep class io.split.android.client.dtos.* { *; }
-keep class io.split.android.client.storage.db.** { *; }
```

**Comment by chillaq** [comment]
Hi Jordan, I will repro the issue locally, could you share the proguard-rules.pro file content?

**Comment by chillaq** [comment]
Hi Jordan, we have a fix for your issue, we are testing the build now, will let you know when it is released.

**Comment by jordansilva** [comment]
> Hi Jordan, I will repro the issue locally, could you share the proguard-rules.pro file content?

Unfortunately, I can't. We have a lot of exclusions and some private packages there that I can't share.  
Now we have those 3 rules specifically for Split.io
```
-dontwarn com.google.common.**
-keep class io.split.android.client.dtos.* { *; }
-keep class io.split.android.client.storage.db.** { *; }
```

**Comment by NicoZelaya** [comment]
Hi @jordansilva ! 

Would you mind testing the version 2.6.2 of this SDK? We added the missing rules to our proguard rules file. 
Let's keep this issue open until you can validate there are no more issues or share any new findings that need a follow up.

Apologies for the inconveniences,
Nico.
