### ISSUE TITLE
Calling removeObserver from wrong thread

### ISSUE THREAD

**Issue by mkotyk-godaddy** [splitio/android-client#200]
I'm seeing these errors in my logs:

```E/SplitSDK: We could not shutdown split
    java.lang.IllegalStateException: Method removeObserver must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.removeObserver(LifecycleRegistry.java:219)
        at io.split.android.client.lifecycle.LifecycleManager.destroy(LifecycleManager.java:37)
        at io.split.android.client.SplitFactoryImpl$1.run(SplitFactoryImpl.java:163)
        at java.lang.Thread.run(Thread.java:919)
```

Looking at the code, you are indeed calling `_lifecycleManager.destroy()` from a non-Main thread.  See https://github.com/splitio/android-client/blob/c9657239f4d9a55cedfe0290d28a6da888a6ab22/src/main/java/io/split/android/client/SplitFactoryImpl.java#L178

**Comment by chillaq** [comment]
Thanks Mark for the info, could you please provide the code that uses the SDK?

Thanks
Bilal

**Comment by mkotyk-godaddy** [comment]
I could, but as you can see from the stack trace, this is entirely in Split's client SDK.

In our code, we ensure to build the factory on the main thread.
```
val splitIOModule = module {
    single {
        ManagedSplitFactory(
            accountChanged = get<AuthenticationProvider>().currentUser,
            logger = get()
        ) { shopperId ->
            val apiKey = BuildConfig.E_SPLITIO_API_KEY.decrypt()
            val matchingKey = shopperId ?: "default"
            val key = Key(matchingKey, null)
            val config = SplitClientConfig.builder().build()
            try {
                // Must be performed on main thread
                runBlocking(Dispatchers.Main) {
                    SplitFactoryBuilder.build(apiKey, key, config, get<Context>())
                }
            } catch (ex: Exception) {
                error(ex)
            }
        }
    }
    single<DynamicFeatureStore> { SplitDynamicFeatureStore(splitFactory = get(), gson = get()) }
}
```

**Comment by chillaq** [comment]
Thanks Mark, we are working on it now.

**Comment by chillaq** [comment]
Hi Mark, We are trying to reproduce the exception and the only setup that allowed us to do it was using androidx.lifecycle:lifecycle-runtime:2.3.0-alpha07 component (alpha version).
Could you provide the version of this library on your side?  We want to confirm we can replicate your scenario to have a way to test the fix properly.

**Comment by mkotyk-godaddy** [comment]
Hi Bilal,

We're not directly importing that particular library, but it might be getting pulled in as a sub-dependency:

```
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0'
```

Those are the only occurrences of `lifecycle` in our build files.  If I navigate the calls, I do end up in `lifecycle-common-2.3.0-alpha06.jar`

Looking at the implementation, it appears `removeObserver` must be called from the main thread going forward, so I think the error still lies in the SplitIO code. 

https://github.com/androidx/androidx/blob/a39a42f4b22f10c0a221023aa8684766cd691513/lifecycle/lifecycle-runtime/src/main/java/androidx/lifecycle/LifecycleRegistry.java#L219

`SplitLifecycleManager` will need to switch threads before calling `removeObserver`

https://github.com/splitio/android-client/blob/c9657239f4d9a55cedfe0290d28a6da888a6ab22/src/main/java/io/split/android/client/lifecycle/SplitLifecycleManager.java#L55

An example of how to do this can be found here https://stackoverflow.com/questions/11123621/running-code-in-main-thread-from-another-thread

**Comment by jordansilva** [comment]
I also had the same issue but with `addObserver` function.
**dependencies:** 
io.split.client:android-client:2.6.6
androidx.lifecycle:lifecycle-runtime-ktx:2.3.0-alpha07

```java
Caused by: java.lang.IllegalStateException: Method addObserver must be called on the main thread
at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
at io.split.android.client.lifecycle.SplitLifecycleManager.<init>(SplitLifecycleManager.java:24)
at io.split.android.client.SplitFactoryImpl.<init>(SplitFactoryImpl.java:169)
at io.split.android.client.SplitFactoryImpl.<init>(SplitFactoryImpl.java:80)
at io.split.android.client.SplitFactoryBuilder.build(SplitFactoryBuilder.java:67)
at **********.SplitIO.initializeClient(SplitIO.kt:90)```

**Comment by chillaq** [comment]
Hi Mark, this issue is fixed in SDK version 2.6.7, could you please upgrade and let us know how it goes.

Thanks
Bilal

**Comment by mkotyk-godaddy** [comment]
Yay, it appears to be fixed now.  Thanks!  🎉

**Comment by chillaq** [comment]
Great, thanks
