### ISSUE TITLE
In app profiling I see 4 threads related to split that are eating up CPU cycles

### ISSUE THREAD

**Issue by KarimFikani** [splitio/android-client#204]
Recently I have been profiling my app and I saw that the top threads that are eating CPU cycles are related to split.

![Screen Shot 2020-09-23 at 2 14 35 PM](https://user-images.githubusercontent.com/2486075/94070600-5a071200-fda7-11ea-9da7-f12f154e8e3b.png)

Is there a reason for that? I already initialized split on app launch and this profile came from going to another activity in my app where I just query split one for a specific feature on activity create and I feel this affects the performance of the app.

**Comment by chillaq** [comment]
Hi Karim, the Split SDK spawn threads that runs continuously to do two things:

1- Sync with the Split cloud for any changes to Splits from UI, so the SDK cache is always updated.
2- Every time you call getTreatment() function, an Impression record is is inserted into the cache, and a thread watches the cache to post any new created impression to Split cloud. Same things if you use client.track() method, which will post an event to Split cloud.

If after calculating the Split treatment, you don't need the SDK anymore, you can call client.Destroy(), this will stop all background threads and disable the factory. You will need to create new factory object if you need it again.

Thanks
Bilal

**Comment by KarimFikani** [comment]
Hey @chillaq thank you for the quick reply. Still have few questions:
-So the more I call getTreatment or getTreatmentWithConfig anew thread is created?
-What is the point of setting the refresh rate if there are thread that constantly listening to any changes? It would make sense to have one running thread that executes on the refreshrate and that thread always pulls the diff from split backend and store it in cache. As for getTreatment should always fetch from cache. Is there a way to configure that? 

I feel that the performance should be improved from splitsdk side as any time I run the profiler I see the split thread on top of the list. Calling destroy every time I'm done with the treatment and re-initializing would affect the performance wouldn't it?

**Comment by chillaq** [comment]
Hi Karim, there is one thread for posting impressions and another for posting events. You can control the frequency of when these threads wake up and check the cache.
I think the continuously running thread is the one connecting to streaming server, this is a websocket connection to sync with Split changes.

I will check internally to confirm this and get back to you.

Thanks
Bilal

**Comment by chillaq** [comment]
Hi Karim, could you please provide the following:
1- SDK version
2- Configuration parameters used and their values

Thanks
Bilal

**Comment by KarimFikani** [comment]
SDK version: 2.6.6
Config in code:

```
val refreshRate = 30 // in debug mode
// val refreshRate = 14400 // 4 hours in release mode
val key = userId ?: DeviceUtils.getDeviceId(context)

// Build SDK configuration by default
val config = SplitClientConfig.builder()
config.featuresRefreshRate(refreshRate)
config.segmentsRefreshRate(refreshRate)
config.impressionsRefreshRate(refreshRate)
// connection timeout is in milliseconds.
config.connectionTimeout(refreshRate)

val builder = config.build()
val k = Key(key, null)

val splitFactory = SplitFactoryBuilder.build(apiKey, k, builder, context)

client = splitFactory.client()
```

**Comment by KarimFikani** [comment]
Saw more threads from split

<img width="987" alt="Screen Shot 2020-09-24 at 12 29 26 PM" src="https://user-images.githubusercontent.com/2486075/94191120-eaa22880-fe61-11ea-9296-a23ca314cba3.png">

**Comment by KarimFikani** [comment]
@chillaq any updates from your end?

**Comment by chillaq** [comment]
Hi Karim, few questions for you:
- What is the Android device and OS version?
- Are you using polling or streaming?
- Is this the regular behaviour or it happens periodically?
- What was the host app doing while the screenshot? Was it idle or doing some work?
- Could you please send us a recorder Sample Java Methods trace and a CPU usage graphic screenshot of about 1 minute of profiling?

**Comment by KarimFikani** [comment]
- What is the Android device and OS version?
Samsung S10+ Android 10
- Are you using polling or streaming?
Polling
- Is this the regular behavior or it happens periodically?
Regular behavior
- What was the host app doing while the screenshot? Was it idle or doing some work?
Doing some work 
- Could you please send us a recorder Sample Java Methods trace and a CPU usage graphic screenshot of about 1 minute of profiling?
The following are screenshots when app is idle on homepage. Low CPU usage 8% but still all effort going to split threads.
<img width="1674" alt="Screen Shot 2020-09-25 at 1 23 15 PM" src="https://user-images.githubusercontent.com/2486075/94312889-9c108f00-ff32-11ea-850f-4c01eee05fa7.png">
<img width="1677" alt="Screen Shot 2020-09-25 at 1 23 37 PM" src="https://user-images.githubusercontent.com/2486075/94312898-a03cac80-ff32-11ea-8ee8-f66591449b31.png">

And here is the trace:
[profiling-idle-state.trace.zip](https://github.com/splitio/android-client/files/5285220/profiling-idle-state.trace.zip)


Screenshots when app is working. CPU usage goes up to 37% and top threads are split threads by thread time and wall clock time:
<img width="1677" alt="Screen Shot 2020-09-25 at 1 31 12 PM" src="https://user-images.githubusercontent.com/2486075/94313630-e9d9c700-ff33-11ea-8426-df6cf596e270.png">
<img width="1675" alt="Screen Shot 2020-09-25 at 1 30 40 PM" src="https://user-images.githubusercontent.com/2486075/94313633-ee05e480-ff33-11ea-9a3d-bca8e325bf89.png">

And here is the trace:
[profiling-doing-work.trace.zip](https://github.com/splitio/android-client/files/5285268/profiling-doing-work.trace.zip)

Here is a sample code of how I'm querying split:
```
    override fun fetchStringConfig(configName: String, attributes: Map<String, Any?>?): String? {
        val result = client?.getTreatmentWithConfig(configName, attributes)
        return when (result?.treatment()) {
            INVALID_TREATMENT -> null
            TREATMENT_ON, TREATMENT_OFF -> fetchConfigHelper(result.config()) as? String
            else -> null
        }
    }

    override fun fetchBooleanConfig(configName: String, attributes: Map<String, Any?>?): Boolean? {
        return when (client?.getTreatment(configName, attributes)) {
            INVALID_TREATMENT -> null
            TREATMENT_ON -> true
            TREATMENT_OFF -> false
            else -> null
        }
    }
```

**Comment by KarimFikani** [comment]
@chillaq any updates from your end?

**Comment by chillaq** [comment]
Hi Karim,

Analyzing your trace we noticed some idle threads that we can remove doing some tuning to our task executor, we will work on a patch.

However, we saw some duplicated Split SDK threads that we could only reproduce by creating more than one sdk factory instance.
- Could it be that you using more than one factory instance at the same time?
- If not, do you create and recreate the factory at some point?

Thanks
Bilal

**Comment by KarimFikani** [comment]
Hey Bilal, yes I do create the factory for every workspace. We have two workspaces, the default one and the android specific one and each has an API key so that's why I'm creating two factories. Is there another way of querying different workspaces on one factory?

**Comment by KarimFikani** [comment]
Also we did some fixes on our end setting up the factory by adding:

```
// Enabling streaming for split
config.streamingEnabled(true)
// Enabling background syncs
config.sychronizeInBackground(true)
config.backgroundSyncWhenBatteryNotLow(true)
config.backgroundSyncWhenWifiOnly(true)
config.sychronizeInBackgroundPeriod(BACKGROUND_SYNC_PERIOD) // 180
```

and we got better results for the same action that I mentioned in my previous comments with these new settings.

<img width="1745" alt="Screen Shot 2020-10-01 at 8 14 44 PM" src="https://user-images.githubusercontent.com/2486075/94884630-ddb5a400-0422-11eb-869c-bdfa84d2e7db.png">
<img width="1749" alt="Screen Shot 2020-10-01 at 8 14 57 PM" src="https://user-images.githubusercontent.com/2486075/94884637-e1492b00-0422-11eb-9d53-9fe7f75df3bf.png">

**Comment by chillaq** [comment]
Great, glad the issue is better now.

**Comment by KarimFikani** [comment]
> Hi Karim,
> 
> Analyzing your trace we noticed some idle threads that we can remove doing some tuning to our task executor, we will work on a patch.
> 
> However, we saw some duplicated Split SDK threads that we could only reproduce by creating more than one sdk factory instance.
> 
> * Could it be that you using more than one factory instance at the same time?
> * If not, do you create and recreate the factory at some point?
> 
> Thanks
> Bilal

@chillaq what is the status of the patch?

**Comment by NicoZelaya** [comment]
Hi @KarimFikani !

We tracked this enhancement in our backlog already to tweak the task executor and optimize, but we don't have a target date for it's release. 

In any case, if this is still causing a measurable bad impact on your end, please share the updated information with us so we can prioritize accordingly. 

If this is the case, something that would help is to be able to see at least the Wall clock time and the CPU time , if possible. 
We want to get a proper idea of how much Split is actually using the CPU vs how much time it's waiting in your case. Any other metrics you can share would also be of help of course.
For the snapshot, it would be good to either get the SDK debug log along with it for the profiled execution, or at least a description of which actions the SDK performed. This would help us understand in case CPU time/Wall clock time < 1, if the wait is on the network, the CPU being busy with something else or the check to SQLite, to name an example.

Let us know your thoughts and my sincere apologies for the delay getting back to you here.
Nico.

**Comment by KarimFikani** [comment]
@NicoZelaya after updating our split settings to this https://github.com/splitio/android-client/issues/204#issuecomment-702504128 performance improved by a lot! Last time I profiled I saw a lot less split threads and they weren't the top ones eating up my cpu cycles. Will let you know if I face any slowdowns from split, for the time being we are good. Thx!
