### ISSUE TITLE
Set user ID without creating a new instance

### ISSUE THREAD

**Issue by stephen1706** [splitio/android-client#210]
Hi, I am planning to use a same instance of SplitClient as a singleton instance, is there a way to set the user ID without creating a new instance? I am also having difficulty to set the user ID correctly, as the targeting rule is not working properly. 
How I am setting the user ID now:
```
val config = SplitClientConfig.builder()
            .impressionsRefreshRate(60)
            .connectionTimeout(10000)
            .readTimeout(10000)
            .build()
val userId = "123"
val splitFactory = SplitFactoryBuilder.build(
            configuration.splitKey,
            Key(userId),
            config,
            application)
val instance = splitFactory.client()
instance.on(SplitEvent.SDK_READY, object: SplitEventTask() {
            override fun onPostExecution(client: SplitClient?) {
                Log.d("test", "SDK_READY")
            }
        })        
```

**Comment by stephen1706** [comment]
@chillaq so I believe I can just re-instantiate a new SplitClient during login and logout?

**Comment by chillaq** [comment]
Yes, just make sure to disable the old factory instance using client.Destroy() before initializing a new factory instance.
