### ISSUE TITLE
Crash caused by WorkManager

### ISSUE THREAD

**Issue by stephen1706** [splitio/android-client#211]
Hi, there is a crash on WorkManager which is caused when calling `SplitFactoryBuilder.build`. It happens only on certain device, it happened on Samsung S20, Android OS 10. I tested on emulator OS 10 is actually working fine. Is there anything I need to define to avoid this? I am using version 2.6.4
My split client initialization code
```
private lateinit var instance: SplitClient

fun refreshInstance(userId: String?) {
        if (this::instance.isInitialized) {
            instance.flush()
            instance.destroy()
        }

        val config = SplitClientConfig.builder()
            .build()

        val splitFactory = SplitFactoryBuilder.build(
            configuration.splitKey,
            Key(userId ?: "GUEST"),
            config,
            application.applicationContext
        )
        instance = splitFactory.client()
    }
```

Location of crash at the Split SDK:
```
//SplitFactoryHelper line 94
    WorkManagerWrapper buildWorkManagerWrapper(Context context, SplitClientConfig splitClientConfig,
                                               String apiKey, String key, String databaseName) {
        return new WorkManagerWrapper(
                WorkManager.getInstance(context), splitClientConfig, apiKey, key, databaseName);

    }
```

**Comment by chillaq** [comment]
Thanks Stephan for the info, will check it and get back to you

**Comment by stephen1706** [comment]
@chillaq thanks. to add more information about this, I call the `SplitFactoryBuilder.build` during Application.onCreate, and my application class does not explicitly implement `Configuration.Provider`
I can repro the bug by running a robolectric test case which call my `refreshInstance` method, then it will show the same error.
Complete stacktrace: 
```
java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.

	at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:146)
	at androidx.work.WorkManager.getInstance(WorkManager.java:181)
	at io.split.android.client.SplitFactoryHelper.buildWorkManagerWrapper(SplitFactoryHelper.java:94)
	at io.split.android.client.SplitFactoryImpl.<init>(SplitFactoryImpl.java:148)
	at io.split.android.client.SplitFactoryImpl.<init>(SplitFactoryImpl.java:80)
	at io.split.android.client.SplitFactoryBuilder.build(SplitFactoryBuilder.java:67)
```

**Comment by stephen1706** [comment]
@chillaq actually it is not device specific, it happens on all device

**Comment by stephen1706** [comment]
@chillaq I manage to resolve the issue, turns out the `SplitFactoryBuilder` is called before `Application.onCreate` which causes the issue

**Comment by chillaq** [comment]
Thanks Stephan, I will create a KB fo this issue.

**Comment by hbb20** [comment]
@stephen1706 Need your help. I am facing similar issue. You mentioned that `I call the SplitFactoryBuilder.build during Application.onCreate` but later you said that  `SplitFactoryBuilder is called before Application.onCreate`. I did not understood that. I am facing similar issue where it's created in onCreate() through dagger. How did you solve this?

**Comment by kareem12599** [comment]
Hey, @stephen1706 @hbb20 I'm facing the same issue, any updates about how to solve it?
