### ISSUE TITLE
Crashes in SplitUpdatesWorker and MySegmentsUpdateWorker

### ISSUE THREAD

**Issue by KarimFikani** [splitio/android-client#212]
Hey!

I have seen crashes with some of our customers related to these two files:

```
MySegmentsUpdateWorker.java line 33
io.split.android.client.service.sseclient.reactor.MySegmentsUpdateWorker.onWaitForNotificationLoop
```

```
SplitUpdatesWorker.java line 32
io.split.android.client.service.sseclient.reactor.SplitUpdatesWorker.onWaitForNotificationLoop
```

Unfortunately no stacktrace was generated from crashlytics, all I got was this:

```
Fatal Exception: java.lang.OutOfMemoryError
OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

```

splitSDKVersion = '2.6.6'
android version = 6.0.1
device = Galaxy S5

**Comment by chillaq** [comment]
Hi Karim, I need to check the API Key used in SDK and which organization in Split it is fetching info, just to see the size of payload coming back to SDK cache.
Could you provide the org name and first four characters of the API Key?

Thanks
Bilal

**Comment by KarimFikani** [comment]
Hey Bilal, yes it's TripActions and we have two workspaces "Default" : "PYBo" and "Android" : "pK0G".

**Comment by chillaq** [comment]
Thanks Karim, I don't see SDK API Keys starts with the characters given, usually they are all in low cap. I wanted to make sure you are using the "Browser" type API Key and not "SDK" type. Could you confirm this?

Thanks
Bilal

**Comment by chillaq** [comment]
Hi Karim, I am following up on this issue, do you still require any assistance?

Thanks
Bilal

**Comment by KarimFikani** [comment]
@chillaq sorry for late response but here are the browser api keys "production" : "s9ol" and "android" : "jtpl". Let me know if you need more info.

**Comment by chillaq** [comment]
Thanks Karim, the API Key looks good, I am running a local app to repro this issue, could you provide the config parameters value used?

**Comment by KarimFikani** [comment]
Not sure I understand what you need here. Do you mean how do I setup SplitClientConfig?

**Comment by chillaq** [comment]
Yep, what are the config parameters passed and their values.

**Comment by KarimFikani** [comment]
```
        // val refreshRate = 14400
        // val CONNECTION_TIME_OUT = 15000 // In milliseconds
        // val BACKGROUND_SYNC_PERIOD: Long = 180 // 3 hrs in minutes 
        val config = SplitClientConfig.builder()
        config.featuresRefreshRate(refreshRate)
        config.segmentsRefreshRate(refreshRate)
        config.impressionsRefreshRate(refreshRate)
        // connection timeout is in milliseconds.
        config.connectionTimeout(CONNECTION_TIME_OUT)
        config.readTimeout(CONNECTION_TIME_OUT)
        // Enabling streaming for split
        config.streamingEnabled(true)
        // Enabling background syncs
        config.sychronizeInBackground(true)
        config.backgroundSyncWhenBatteryNotLow(true)
        config.backgroundSyncWhenWifiOnly(true)
        config.sychronizeInBackgroundPeriod(BACKGROUND_SYNC_PERIOD)
```

**Comment by chillaq** [comment]
Thanks Karim, I tried to repro using polling mechanism and running app for an hour against your org, did not see any OOM exceptions. 
I will get the Android developer engaged, do you still see this exception and/or can you repro locally on your side?

**Comment by KarimFikani** [comment]
@chillaq I've been monitoring and doesn't seem it's happening anymore. Will close it for now and will reopen if it shows up again. Thanks!
