### ISSUE TITLE
name: android.database.sqlite.SQLiteFullException database or disk is full (code 13)

### ISSUE THREAD

**Issue by gaurav-girish** [splitio/android-client#219]
This crash on Android app has seen an increase after 31st December 2020. Full crash stack below.
Attached is the report from Embrace. 
[Embrace - Crash Details.pdf](https://github.com/splitio/android-client/files/5778304/Embrace.-.Crash.Details.pdf)

at android.database.sqlite.SQLiteConnection.nativeExecute (Native Method)
--
  | at android.database.sqlite.SQLiteConnection.execute (SQLiteConnection.java:569)
  | at android.database.sqlite.SQLiteSession.endTransactionUnchecked (SQLiteSession.java:439)
  | at android.database.sqlite.SQLiteSession.endTransaction (SQLiteSession.java:403)
  | at android.database.sqlite.SQLiteDatabase.endTransaction (SQLiteDatabase.java:588)
  | at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction (FrameworkSQLiteDatabase.java:90)
  | at androidx.room.RoomDatabase.endTransaction (RoomDatabase.java:364)
  | at io.split.android.client.storage.db.ImpressionDao_Impl.insert (ImpressionDao_Impl.java:5)
  | at io.split.android.client.storage.impressions.SqLitePersistentImpressionsStorage.push (SqLitePersistentImpressionsStorage.java:20)
  | at io.split.android.client.storage.impressions.SqLitePersistentImpressionsStorage.push (SqLitePersistentImpressionsStorage.java:20)
  | at io.split.android.client.service.synchronizer.RecorderSyncHelperImpl$1.run (RecorderSyncHelperImpl.java:66)
  | at java.lang.Thread.run (Thread.java:761)

**Comment by chillaq** [comment]
Hi Gaurav, thanks for the info, we will release a patch by end of week.

Thanks
Bilal

**Comment by gaurav-girish** [comment]
Hello Bilal,
Would this be a patch on your server side or the Android sdk?
Thanks
Gaurav

**Comment by chillaq** [comment]
It will be Android SDK patch
