### ISSUE TITLE
Very slow startup, split consuming 100% CPU

### ISSUE THREAD

**Issue by mkotyk-godaddy** [splitio/android-client#224]
Hi guys,

I'm seeing a new issue on startup causing our app to take 140 seconds to start and using 100% cpu during that time.

I've tracked the hot spot down to  BCrypt.java:641-644 where it does 1024 rounds initializing the key.

```
crypt_raw:639, BCrypt (io.split.android.client.utils)
hashpw:710, BCrypt (io.split.android.client.utils)
convertApiKeyToFolder:88, Utils (io.split.android.client.utils)
buildDatabaseName:54, SplitFactoryHelper (io.split.android.client)
<init>:135, SplitFactoryImpl (io.split.android.client)
<init>:84, SplitFactoryImpl (io.split.android.client)
build:67, SplitFactoryBuilder (io.split.android.client)
<GoDaddy Code>
```

As an aside it is a universally bad idea to roll your own cryptography instead of using what is built into the platform, as you take on the responsibility of any security vulnerabilities and updates.

**Comment by mkotyk-godaddy** [comment]
Here's an example using the android APIs, which likely benefit from hardware acceleration.

https://developer.android.com/guide/topics/security/cryptography

**Comment by chillaq** [comment]
Hi @mkotyk-godaddy , thanks for the info, could you provide the following:

1- Code that is using the SDK
2- Which version of the SDK are you using?
3- Enable SDK debug logging and paste it here.

Thanks
Bilal

**Comment by chillaq** [comment]
Hi @mkotyk-godaddy , the code looks ok, there might be an issue with SDK sending http requests or using the websocket connection to fetch the data.

Can you download the Android project from this KB: https://help.split.io/hc/en-us/articles/360015345052-Android-App-Project-using-Split-SDK-example-
Then upgrade Split SDK and let me know if the project works or you see the same issue.

Thanks
Bilal

**Comment by mkotyk-godaddy** [comment]
Hi @chillaq,  I don't think this issue is a bug, but more of a design choice.  Using a Blowfish algorithm at 1024 rounds might be a good way to secure the client id on a desktop, but on a wide range of mobile devices that may have 1/100th the computing power of a desktop, it creates an un-usable experience.  

Our app simply can't wait 2 minutes or more while splitio tries to computes the filename of the Room database to open.

I would suggest to the engineers to use a simpler hashing algorithm and then dropping some data.  I think it would still create a sufficiently unique database filename while making it impossible to brute force a client id.

**Comment by mkotyk-godaddy** [comment]
I've suggested a possible fix https://github.com/splitio/android-client/pull/225

**Comment by mkotyk-godaddy** [comment]
Well on further runs, sometimes it's slow, sometimes it's normal.

**Comment by javrudsky** [comment]
Hi @mkotyk-godaddy,
Thank you for your PR. Currently we're considering merging it but first we'd like to reproduce this behaviour to be sure that there isn't other related issue. Until now, we've tried to do that without success, so any information you can provide to us would be very helpful. Maybe some scenario in which the issue normally occurs, or any specific device or OS version.
Also, any other information you consider relevant would be appreciated.
