### ISSUE TITLE
Android Custom Widgets and Keyboard not getting updated Split Partitions Value when Apps is in Background

### ISSUE THREAD

**Issue by BillyKaleb** [splitio/android-client#237]
Hi Team,

I'm experiencing a problem with Split Configuration when using Split in Widgets and Keyboard, where our Widgets / Keyboard is not getting an updated value (After changes in Dashboard, of course) if i don't open the main app to foreground.

I've been trying to trace the problem until `SplitsStorageImpl.java` class where after some delay after Dashboard changes, i'm getting an update and `mInMemorySplits` variable is updated with proper value. But as long as i let the main apps stay in background, whenever i'm getting value from `SplitsStorageImpl.java` from Widgets it'll still get the old non-updated value.

Currently i'm assuming that our Widgets / Keyboard is not holding the same instances of `mInMemorySplits` that being updated in `update()` method, and because split uses local variable instead of database update (i see that database update only called in `loadLocal()`), our Widgets / Keyboard somehow miss the references. I'll keep trying to trace the problem on my side and get back if i got a new info.

My main question is whether there's any need for specific configuration for these cases? I'm currently toggling on all background-related config i found in https://help.split.io/hc/en-us/articles/360020343291-Android-SDK#configuration although to no result.

Thanks before.

**Comment by chillaq** [comment]
Hi @BillyKaleb, Have you enable the config parameters to allow synching the cache when the app is in the background? if this is allowed, whatever changes made in Split UI will be synched to the SDK cache.

Can you provide the SDK code used in your app and the config parameters values? will check it on my side.

Thanks
Bilal

**Comment by BillyKaleb** [comment]
Hi @chillaq, thanks for the reply

I think the config for allowing synching the cache when the app is in the background is `synchronizeInBackground()`? If it is, then it's already turned on along with some other background related config.

Our current config is as below:

>ToggleClientConfig.Builder()
> .setConnectionTimeout(15_000)
> .setEnableDebug(BuildConfig.DEBUG)
> .setSynchronizeInBackground(true)
> .setStreamingEnabled(true)
> .setBackgroundSyncWhenBatteryNotLow(false)
> .setReady(15_000)
> .build()

Currently i'm playing around with `setBackgroundSyncWhenBatteryNotLow()`, but it seems like there's no changes.

Also our current Split version is `2.6.8`, maybe that could help somehow?

Thanks again.

**Comment by chillaq** [comment]
Hi @BillyKaleb , I tried the following scenario below and I am able to repro the issue:

1- Ran the simple code below to repro the issue, started the app, treatment calculated correct.
2- Set the app in the background
3- Made a change to the Split, default treatment from on->off
4- I see the Split change notification in the device log, but the SDK still did not fetch the new split changes.
5- Brought the app back up, treatment is still incorrect off. 
6- I see the SDK fetching the split new changes now.

I will check with Engineering to see how to have sync in background work.

public class MainActivity extends AppCompatActivity {
    SplitClient client = null;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        String apikey = "API KEY";

        SplitClientConfig config = SplitClientConfig.builder()
                .sychronizeInBackground(true)
                .enableDebug()
                .build();
        String matchingKey = "testing1234";
        String bucketingKey = null;
        Key k = new Key(matchingKey, bucketingKey);
        try {
            SplitFactory splitFactory = SplitFactoryBuilder.build(apikey, k, config, getApplicationContext());
            client = splitFactory.client();
            client.on(SplitEvent.SDK_READY, new SplitEventTask() {
                @Override
                public void onPostExecutionView(SplitClient client) {
                    Log.d("split", "Split SDK is READY");
                     String treatment = client.getTreatment("clients");
                            Log.d("split", "Treatment is :" + treatment);
                }
            });
        } catch (Exception e) {

        }

    }
    @Override
    public void onResume(){
        super.onResume();
        Log.d("split", "App is back up");
        String treatment = client.getTreatment("clients");
        Log.d("split", "Treatment is :" + treatment);
    }
}

**Comment by BillyKaleb** [comment]
Hi @chillaq, thanks for the updates!

I hope you could find the fix for this particular bug. I'll try to look for a possible fix from my side too.

Thanks.

**Comment by chillaq** [comment]
Hi @BillyKaleb, I have an update from the team, When the app goes in the background, it can only fetch the Split changes every 15 mins, this is a limitation on the Android services. 
So even if it received the notification when a split is changed, it has to wait for 15 min before fetching the changes and update the cache.

If the app came to the foreground before 15 mins, then the SDK detects there is a change notification and does a fetch request, which the scenario we see here.

So this is by design, not a bug.

Hope that helps.

Thanks
Bilal

**Comment by BillyKaleb** [comment]
Hi @chillaq , sorry for the late reply, and thanks for the answer. I've been testing on my side too, and after reading about Android Services and it's limitations, i can see the intention on this.

Another question is whether there's a possible workaround for this? I think it's doable with some tinkering from our side, but i wonder if there's a recommended method from your teams.

Thanks so much for the answer.

**Comment by chillaq** [comment]
Hi @BillyKaleb , as I mentioned, this is a limitation from Android OS, not sure how to work around it.

Let me know if you find any workaround it.

Thanks
Bilal

**Comment by javrudsky** [comment]
Closing this issue because it has been inactive for one year.

**Comment by javrudsky** [comment]
Closing this issue because it has been inactive for one year.
