### ISSUE TITLE
[v2.13.1] Splits with custom targeting rules always return `control` 

### ISSUE THREAD

**Issue by hackertronix** [splitio/android-client#441]
Hi, 

We're using the Android Client v2.13.1 in our app and lately all the splits that have custom targeting rules are coming back with a value of `control` instead of `on` or `off`

We've followed the docs [here](https://help.split.io/hc/en-us/articles/360020528072-Control-treatment) and are using the `SplitEvent.SDK_READY` to get the treatments but that hasn't helped

Here's the code snippet

```
override fun retrieveFeatureWithAttributeFromApi(
        feature: SplitFeature,
        attributes: Map<String, String>,
        statusRetrieved: (status: FeatureStatus) -> Unit
    ) {
        if (this::splitClient.isInitialized) {
            splitClient.on(
                SplitEvent.SDK_READY,
                object : SplitEventTask() {
                    override fun onPostExecution(client: SplitClient) {}
                    override fun onPostExecutionView(client: SplitClient) {
                        when (client.getTreatment(feature.label, attributes).uppercase()) {
                            "ON" -> statusRetrieved(FeatureStatus.ON)
                            "OFF" -> statusRetrieved(FeatureStatus.OFF)
                            else -> statusRetrieved(FeatureStatus.UNKNOWN)
                        }
                    }
                }
            )
        } else {
            Log.e(
                TAG_FEATURE_FLIPPER,
                "Cannot retrieve features on uninitialized feature flipper instance"
            )
        }
    }
```

And here's what we get when we call `client.getTreatment(features, attributes)`

```
{
  "android-split-test": "control",
  "cross-platform-upgrades": "control",
  "ideas-v0": "off",
  "android-selected-profile-id-refactor": "control",
  "android-ideas-url-highlighting": "control",
  "android-attributes-test": "off",
  "android-edit-update-using-model": "control",
  "android-app-tour": "off",
  "ideas-android-share-extension": "control"
}
```

Would help us a lot if we got a pair of eyes on this. Thanks! 😇

**Comment by agustinona** [comment]
Hi @hackertronix,

It seems all of the splits that are returning correct treatments are defined in your staging environment, while the ones that are returning control are only defined in your prod environment. So it seems likely your are either using a staging api key when you intended to use a prod one, or you defined your splits with custom targeting rules in prod when you actually meant to create them in stage. Could you check if that's the case?

Best,
Agus

**Comment by agustinona** [comment]
Hi @hackertronix,

Were you able to look into this?

**Comment by agustinona** [comment]
Hi @hackertronix this issue has been inactive for a while now so I'm closing it. If you still need assistance please don't hesitate to reach back out.
