### ISSUE TITLE
okhttp3 outdated version

### ISSUE THREAD

**Issue by eldercampanha** [splitio/android-client#466]
One of our security tools have detected a high security vulnerability on the okhttp3 version used by `io.split.client`

The SDK is currently using `com.squareup.okhttp3:okhttp@3.12.0` and the vulnerability has been fixed on version `com.squareup.okhttp3:okhttp@4.9.2` and above.

https://mvnrepository.com/artifact/io.split.client/android-client/3.1.0 

Can we upgrade this library?

Best Regards,
Elder Baltazar

**Comment by agustinona** [comment]
Hi @eldercampanha,

Thanks for the report. Our team will look into this

**Comment by eldercampanha** [comment]
Hi @agustinona , any news regards this issue?
