### ISSUE TITLE
(Network) Instrumentation/Telemetry on top of OkHttp

### ISSUE THREAD

**Issue by echohikaru** [splitio/android-client#567]
Hi, we want to integrate instrumentation SDK that should be put on top of OkHttp instance.
Any plan to take out the OkHttp "instantiator" into caller code, so we can set/modify the OkHttp instance by ourself? or
Any workaround that we can do for now?

Currently we are planning to look at how Firebase Performance bytecode manipulation to put OkHttp instrumentation.

Thank you

**Comment by hbqdev** [comment]
Hi @echohikaru 
We have filed an RFE with our product team for future consideration.

Unfortunately at the moment we do not have any workaround

Regards
